version: '3'
services:
  nlp:
    build:
      context: .
      dockerfile: nlp.Dockerfile
    volumes:
      - $PWD:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  tensorboard:
    build:
      context: .
      dockerfile: tensorboard.Dockerfile
    command: "tensorboard --logdir /app/runs --bind_all"
    volumes:
      - $PWD:/app
    ports:
      - 6006:6006
